import '@/styles/globals.css'
import type { AppProps } from 'next/app'
import { ChakraProvider } from '@chakra-ui/react';
// import Header from '@/components/header'
import Head from 'next/head'
import { useState } from 'react'

export default function App({ Component, pageProps }: AppProps) {
{/* <Avatar size={['sm','lg','lg']} src='https://avatars.githubusercontent.com/u/49856315?v=4' /> */}
  return (
  <ChakraProvider>
    <Head>
        <title>Daniyal - Portfolio</title>
        <meta name="description" content="Generated by Daniyal" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href='https://avatars.githubusercontent.com/u/49856315?v=4' />
      </Head>
    
  <Component {...pageProps} />
  </ChakraProvider>
  )
}
